name: build

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    name: "Redis ${{ matrix.redis-version }}, Ruby ${{ matrix.ruby-version }}, RSpec ${{ matrix.rspec-core-version }}"
    strategy:
      matrix:
        redis-version: [6]

        ruby-version:
          - 3.4

        rspec-core-version:
          - 3.11.0
          - 3.12.3
          - 3.13.5
        include:
          - redis-version: 7
            ruby-version: '3.4'
            rspec-core-version: 3.13.5
          - redis-version: 6
            ruby-version: '4.0.0-preview2'
            rspec-core-version: 3.13.5
          - redis-version: 6
            ruby-version: '3.3'   # Quoted in order to stringify to '3.0', not '3'.
            rspec-core-version: 3.13.5

    services:
      redis:
        image: "redis:${{ matrix.redis-version }}"
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1
        env:
          RSPEC_CORE: ${{ matrix.rspec-core-version }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rubocop
      - run: bundle exec rake
