name: build

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    name: "Redis ${{ matrix.redis-version }}, Ruby ${{ matrix.ruby-version }}, RSpec ${{ matrix.rspec-core-version }}"
    strategy:
      matrix:
        redis-version: [5]

        ruby-version:
          - 2.5

        rspec-core-version:
          - 3.8.2
          - 3.9.3
          - 3.10.1
          - 3.11.0
        include:
          - redis-version: 5
            ruby-version: 3.1
            rspec-core-version: 3.11.0
          - redis-version: 5
            ruby-version: '3.0'   # Quoted in order to stringify to '3.0', not '3'.
            rspec-core-version: 3.11.0

    services:
      redis:
        image: "redis:${{ matrix.redis-version }}"
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: ruby/setup-ruby@922ebc4c5262cd14e07bb0e1db020984b6c064fe # v1
        env:
          RSPEC_CORE: ${{ matrix.rspec-core-version }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rubocop
      - run: bundle exec rake
